[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "imx-unified"
version = "0.1.0"
description = "Unified conversation MVP"
requires-python = ">=3.11"
dependencies = ["cryptography"]

[tool.pytest.ini_options]
testpaths = ["tests"]
